### PR TITLE
Example bot fixes

### PR DESCRIPTION
**Pull request by ryanwinchester**
fix a couple of compile errors

### CODE REVIEW

**Comment by shymega** [comment]
Looks good from a quick scan through.. has this been tested though?

**Comment by ryanwinchester** [comment]
I'm currently building a bot, and started with that example. Added the changes I needed to do to make mine compile.

**Comment by bitwalker** [comment]
Thanks for the PR! It's much appreciated :)

**Comment by shymega** [comment]
@ryanwinchester Apologies for the late reply. Sounds good [the bot]. Got any Github repos for it? I was thinking it would be great to get a list of projects that use `exirc` - like a "hall of fame" thing. :smile:

**Comment by ryanwinchester** [comment]
@shymega i'll try to remember to link it when i push it up.

**Comment by shymega** [comment]
@ryanwinchester Great stuff. Good luck with your bot building.

Also, thanks for the PR - @bitwalker beat me there :+1:

**Comment by ryanwinchester** [comment]
@shymega https://github.com/ryanwinchester/kuma

big plans to refactor to allow different adapters, like irc and slack, etc.
similar to hubot. for now though i just need to figure out macros

**Comment by shymega** [comment]
@ryanwinchester Sounds great! I'm working on an amendment to the README now, going to put a link to your bot in there :)

**Comment by ryanwinchester** [comment]
So, I've actually switched to [hedwig](https://github.com/hedwig-im/hedwig), and using the [hedwig_irc](https://github.com/jeffweiss/hedwig_irc) adapter (that uses exirc).

It's doing everything I want as long as he accepts [my PR to hedwig_irc](https://github.com/jeffweiss/hedwig_irc/pull/3).

**Comment by shymega** [comment]
I'm glad you found a solution that works best for you. I hope the PR goes well :+1:

Hedwig looks interesting. I may use it. Good luck in your future endeavors.

**Pull request merged**
