### PR TITLE
Fix namespaces

### PR DESCRIPTION
**Pull request by tchoutri**
The tests look just fine on my machine. I think it's read to be merged.

### CODE REVIEW

**Comment by shymega** [comment]
Hello,

Théophile Choutri <notifications@github.com> writes:

> The tests look just fine on my machine. I think it's read to be merged.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/bitwalker/exirc/pull/76
>
> -- Commit Summary --
>
>   * Rename the namespaces to be consistent
>   * Fix the test files with the good namespace
>
> -- File Changes --
>
>     M lib/exirc/channels.ex (2)
>     M lib/exirc/client.ex (80)
>     M lib/exirc/commands.ex (4)
>     M lib/exirc/example_handler.ex (10)
>     M lib/exirc/irc_message.ex (2)
>     M lib/exirc/utils.ex (8)
>     M lib/exirc/whois.ex (2)
>     M test/commands_test.exs (4)
>     M test/utils_test.exs (34)
>
> -- Patch Links --
>
> https://github.com/bitwalker/exirc/pull/76.patch
> https://github.com/bitwalker/exirc/pull/76.diff

This PR looks good, IMHO. I would say its good to be merged.

It would be a good idea to make a new major release once this PR has
been merged, though - especially given that a WHOIS PR has also been
merged. @bitwalker - would you agree with this suggestion?

I'm also going to make a PR to bump the Elixir version in `mix.exs` up
to `1.4` as well :)

--
Best regards,
Dom Rodriguez (shymega / dzr).

**Comment by tchoutri** [comment]
I have a last PR to submit before the next release, that will implement WHO, thanks to @hrefhref. :)

**Comment by hrefhref** [comment]
I concurr. I've done [this work](https://github.com/bitwalker/exirc/compare/master...hrefhref:develop) years ago -- it'd be definitely useful, but I don't have the time to fix it against master &such -- I'll let @tchoutri do the hard work ; )

**Comment by tchoutri** [comment]
@bitwalker If that's okay for your, and in order to simplify development for the next PRs, I suggest that you merge this branch into master so we don't bother rebasing everything for the other branches that will be created for the next major release. :)

**Comment by tchoutri** [comment]
@bitwalker Hi! I hope you're alright :) Just wanted to know if you had seen my previous message (and what you think about it)

**Pull request merged**
